const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'index.html'), 'utf8')

test('web app exposes master output and own GPS fault controls', () => {
  assert.match(html, /id="outputEnabled"/)
  assert.match(html, /Run simulator/)
  assert.match(html, /id="outputStatus"/)
  assert.match(html, /id="ownGpsFault"/)
  assert.match(html, /id="ownHeadingEnabled"/)
  assert.match(html, /id="resetOwn"/)
  assert.match(html, /Simulate compass heading/)
  assert.match(html, /Lost\/Intermittent for DR testing/)
  assert.match(html, /id="ownSpeedSelf" type="number" min="0" max="999"/)
  assert.match(html, /id="ownSpeedRoute" type="number" min="0" max="999"/)
})

test('web app groups simulator controls into top-level tabs', () => {
  assert.match(html, /data-tab="ais"[\s\S]*AIS Vessels/)
  assert.match(html, /data-tab="environment"[\s\S]*Environment/)
  assert.match(html, /data-tab="own"[\s\S]*Own Vessel/)
  assert.match(html, /data-tab-panel="ais"/)
  assert.match(html, /data-tab-panel="environment"/)
  assert.match(html, /data-tab-panel="own"/)
  assert.match(html, /function selectTab\(tabName\)/)
})

test('web app exposes own boat start position controls', () => {
  assert.match(html, /Own Boat Start/)
  assert.match(html, /id="startLatitude"/)
  assert.match(html, /id="startLongitude"/)
  assert.match(html, /id="saveStartPosition"/)
  assert.match(html, /id="useCurrentStart"/)
  assert.match(html, /Use current position/)
  assert.match(html, /\/own\/start-position/)
})

test('web app exposes GPX route loading controls', () => {
  assert.match(html, /GPX Route/)
  assert.match(html, /id="gpxFile"/)
  assert.match(html, /id="selectGpxFile"/)
  assert.match(html, /Choose GPX file/)
  assert.match(html, /id="gpxRouteName"/)
  assert.match(html, /id="restartGpxRoute"/)
  assert.match(html, /aria-label="Restart route"/)
  assert.match(html, /id="playGpxRoute"/)
  assert.match(html, /aria-label="Play route"/)
  assert.match(html, /id="pauseGpxRoute"/)
  assert.match(html, /aria-label="Pause route"/)
  assert.match(html, /id="stopGpxRoute"/)
  assert.match(html, /aria-label="Stop route"/)
  assert.match(html, /\/own\/gpx-route\/playback/)
  assert.match(html, /id="clearGpxRoute"/)
  assert.match(html, /route-status/)
  assert.match(html, /parseGpxPoints/)
  assert.match(html, /\/own\/gpx-route/)
  assert.match(html, /setInterval\(refresh, 5000\)/)
  assert.doesNotMatch(html, /gpxFile\.value = ""/)
})

test('web app exposes own vessel motion modes', () => {
  assert.match(html, /data-motion-mode="stationary"[\s\S]*Docked \/ anchored/)
  assert.match(html, /Self steering at 0 kn to test drifting in tide/)
  assert.match(html, /data-motion-mode="self"[\s\S]*Self steering/)
  assert.match(html, /data-motion-mode="route"[\s\S]*GPX route/)
  assert.match(html, /data-motion-panel="stationary"/)
  assert.match(html, /data-motion-panel="self"/)
  assert.match(html, /data-motion-panel="route"/)
  assert.match(html, /\/own\/motion-mode/)
  assert.match(html, /function renderMotionMode\(mode\)/)
  assert.match(html, /panel\.classList\.toggle\("active", panel\.dataset\.motionPanel === mode\)/)
})

test('web app keeps target actions and toggles in separate columns', () => {
  assert.match(html, /grid-template-columns: minmax\(160px, 1fr\) 78px 76px 132px 116px 152px 58px/)
  assert.match(html, /\.target-actions[\s\S]*grid-template-columns: repeat\(4, 34px\)/)
  assert.match(html, /toggles\.className = "target-toggles"/)
})

test('web app controls environment variation', () => {
  assert.match(html, /id="environmentEnabled"/)
  assert.match(html, /Publish simulated environment/)
  assert.match(html, /id="depthVarying"/)
  assert.match(html, /id="windVarying"/)
  assert.match(html, /id="currentVarying"/)
  assert.match(html, /id="environmentVariationEnabled"/)
  assert.match(html, /Vary depth, wind and tide/)
  assert.doesNotMatch(html, /Enable variation/)
  assert.doesNotMatch(html, /Disable variation/)
  assert.match(html, /function setEnvironmentVariation\(enabled\)/)
})

test('web app exposes bulk AIS target controls', () => {
  assert.match(html, /Let AIS vessels make automatic turns/)
  assert.match(html, /checkbox\("AR"/)
  assert.match(html, /miniButton\("←"/)
  assert.match(html, /miniButton\("→"/)
  assert.doesNotMatch(html, /miniButton\("L"/)
  assert.doesNotMatch(html, /miniButton\("R"/)
  assert.match(html, /id="enableAllTargets"/)
  assert.match(html, /id="disableAllTargets"/)
  assert.match(html, /\/targets\/autopilot/)
  assert.match(html, /function setAllTargets\(enabled\)/)
})

test('web app relies on automatic state refresh without a manual update button', () => {
  assert.match(html, /setInterval\(refresh, 5000\)/)
  assert.doesNotMatch(html, /id="refresh"/)
  assert.doesNotMatch(html, />Update now</)
})

test('web app labels auto-reverse without autopilot wording', () => {
  assert.match(html, /Auto-reverse Test/)
  assert.match(html, /Auto-reverse heading/)
  assert.match(html, /Reverse after seconds/)
  assert.match(html, /\/own\/auto-reverse/)
  assert.doesNotMatch(html, />Autopilot</)
  assert.doesNotMatch(html, /Route autopilot/)
})

test('web app wires keyboard arrows to own boat controls', () => {
  assert.match(html, /document\.addEventListener\("keydown", handleKeyboardControls\)/)
  assert.match(html, /event\.key === "ArrowLeft"[\s\S]*\/own\/heading[\s\S]*direction: "left"/)
  assert.match(html, /event\.key === "ArrowRight"[\s\S]*\/own\/heading[\s\S]*direction: "right"/)
  assert.match(html, /event\.key === "ArrowDown"[\s\S]*\/own\/speed[\s\S]*direction: "down"/)
  assert.match(html, /event\.key === "ArrowUp"[\s\S]*\/own\/speed[\s\S]*direction: "up"/)
})
